apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: TUxPcHNCZXN0VGVhbQ==
  GF_SECURITY_ADMIN_USER: QWRtaW4=                     # Base64 encoded username (e.g., "admin")
