apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "celestial-bodies-classifier"
        static_configs:
          - targets: ["localhost:8001"]

    rule_files:
      - /etc/prometheus/celestial_bodies_rules.yml

  celestial_bodies_rules.yml: |
    groups:
      - name: celestial_bodies_alerts
        rules:
          - alert: HighRequestLatency
            expr: rate(http_request_duration_seconds_sum[5m]) > 0.5
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High request latency detected"
