apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    rule_files:
      - /etc/prometheus/celestial_bodies_rules.yml

    scrape_configs:
      # Scrape config for your celestial-bodies-classifier service
      - job_name: "celestial-bodies-classifier"
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: celestial-bodies-classifier
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: default
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http

      # Scrape config for Node Exporter
      - job_name: "node-exporter"
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: node-exporter-prometheus-node-exporter
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: default

  celestial_bodies_rules.yml: |
    groups:
      - name: celestial_bodies_alerts
        rules:
          - alert: HighRequestLatency
            expr: rate(http_request_duration_seconds_sum[5m]) > 0.5
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High request latency detected"
              description: "Request latency is too high. Investigate the service performance."
