apiVersion: v1
kind: Service
metadata:
  name: celestial-bodies-classifier
  labels:
    app: celestial-bodies-classifier
    model_type: baseline
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: celestial-bodies-classifier
    model_type: baseline
