apiVersion: apps/v1
kind: Deployment
metadata:
  name: celestial-bodies-classifier-canary-deployment
  labels:
    app: celestial-bodies-classifier
    model_type: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celestial-bodies-classifier
      model_type: canary
  template:
    metadata:
      labels:
        app: celestial-bodies-classifier
        model_type: canary
    spec:
      containers:
      - name: celestial-bodies-classifier
        image: europe-west6-docker.pkg.dev/a-guide-to-mlops-438607/mlops-celestial-bodies-classifier-rotf/celestial-bodies-classifier:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: APP_PORT
            value: "3000"
          - name: BENTOML_APISERVER_WORKERS
            value: "1"
          - name: MODEL_TYPE
            value: "ptq_integer"
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
