apiVersion: v1
kind: Service
metadata:
  name: celestial-bodies-classifier
  labels:
    app: celestial-bodies-classifier
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000            # External port
      targetPort: 3000      # Internal container port
  selector:
    app: celestial-bodies-classifier
